/* eslint-env mocha */
'use strict'

describe('browser.js', () => {
  require('./browser/okex.js')
  require('./browser/binance.js')
  require('./browser/bithumb.js')
  require('./browser/huobi.js')
  require('./browser/hitbtc.js')
  require('./browser/bitfinex.js')
  require('./browser/zb.js')
  require('./browser/lbank.js')
  require('./browser/quolinex.js')
  require('./browser/bibox.js')
  require('./browser/gate.js')
  require('./browser/fcoin.js')
  require('./browser/coinex.js')
  require('./browser/coinpark.js')
  require('./browser/coinbig.js')
  require('./browser/coin.js')
  require('./browser/calc.js')
  require('./browser/strategy.js')
  require('./browser/risk.js')
  require('./browser/utils.js')
})
