/* eslint-env mocha */
'use strict'

describe('node.js', () => {
  // require('./node/okex.js')
  require('./node/binance.js')
  require('./node/bithumb.js')
  // require('./node/huobi.js')
  // require('./node/hitbtc.js')
  // require('./node/bitfinex.js')
  // require('./node/zb.js')
  // require('./node/lbank.js')
  // require('./node/quolinex.js')
  // require('./node/bibox.js')
  // require('./node/gate.js')
  // require('./node/fcoin.js')
  // require('./node/coinex.js')
  // require('./node/coinpark.js')
  // require('./node/coinbig.js')
  // require('./node/coin.js')
  // require('./node/calc.js')
  // require('./node/strategy.js')
  // require('./node/risk.js')
  // require('./node/utils.js')
})
